name: Ls Perf Test 8

on:
  push:
    branches:
      - master
      - ls-perf-tests-8
  workflow_dispatch:

jobs:
  ubuntu_build:
    name: Build with tests on Ubuntu
    runs-on: ubuntu-latest
    timeout-minutes: 75

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17.0.7'

      - name: Initialize sub-modules
        run: git submodule update --init

      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ github.sha }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Build with Gradle
        env:
          packageUser: ${{ github.actor }}
          packagePAT: ${{ secrets.GITHUB_TOKEN }}
          LS_PERFORMANCE_TEST_IN_GITHUB_WORKFLOW: true
        run: |
          export DISPLAY=':99.0'
          chmod +x perf_test.sh & ./perf_test.sh
